# Generated by Django 2.1.5 on 2019-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('clothesID', models.IntegerField(primary_key=True, serialize=False)),
                ('clotheGenres', models.CharField(max_length=50)),
                ('clotheName', models.CharField(max_length=100)),
            ],
        ),
    ]
